name: Deploy dev
on:
  push:
    branches: [ master ]

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    env:
      ENV_FILE: ${{ vars.DEV_ENV_FILE }}
    strategy:
      matrix:
        node-version: [20.x]
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'npm'
      - name: Install packages
        run: npm i
      - name: Generate env for project
        run: echo "$ENV_FILE" > .env
      - name: Build project
        run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
         apiToken: ${{ secrets.CF_API_TOKEN }}
         accountId: ${{ secrets.CF_ACCOUNT_ID}}
         projectName: ethglobal-frontend
         directory: ./dist
         branch: main
         gitHubToken: ${{ secrets.GITUB_TOKEN }}